version: '3'
services:
  nestjs-app:
    build:
      context: .
    ports:
      - '3001:3001'
    container_name: learner-ai
    restart: always
    networks:
      - ai-network
    environment:
      - .env

networks:
  ai-network:
    driver: bridge






